<script>


<launch>
	<solver> C:\Documents and Settings\Hester_lab\Desktop\Hummod_Constellation\solver\Code\Model Solver.EXE </solver>
	<model> C:\Documents and Settings\Hester_lab\Desktop\small-stoch-model\HumMod.DES </model>
</launch>

<skipaheadonerror/>
<scramble/>

<?include VarRoster.Script ?>
<?include ParmRoster.Script ?>
<?include RandRoster.Script ?>

<dumproster>
  <filename> Test.txt</filename>
</dumproster>

<continueonerror/>

<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>

<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>

<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>

<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>

<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>


<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>

<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>

<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>

<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>

<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>
<?include MaxCO.Script ?>


</script>
